flow:
    simple_workflow:
        inputs:
            - dataset
        nodes:
            fft_fit:
                type: transform
                operation: fit
                transform: abs_fft
                # transform: FFT
                input:
                    - dataset
            fft_transform:
                type: transform
                operation: transform
                input:
                    - fft_fit
                    - dataset
            resample_fit:
                type: transform
                operation: fit
                transform: resampler_150_samples
                # transform: FFT
                input:
                    - fft_transform
            resample_transform:
                type: transform
                operation: transform
                input:
                    - resample_fit
                    - fft_transform
            random_forest_fit:
                type: estimator
                operation: fit
                estimator: rf_1000
                # estimator: RandomForestClassifier
                input:
                    - resample_transform

    simple_workflow_predict:
        inputs:
            - dataset
            - trained_model
        nodes:
            fft_fit:
                type: transform
                operation: fit
                transform: abs_fft
                # transform: FFT
                input:
                    - dataset
            fft_transform:
                type: transform
                operation: transform
                input:
                    - fft_fit
                    - dataset
            resample_fit:
                type: transform
                operation: fit
                transform: resampler_150_samples
                # transform: FFT
                input:
                    - fft_transform
            resample_transform:
                type: transform
                operation: transform
                input:
                    - resample_fit
                    - fft_transform
            random_forest_classify:
                type: estimator
                operation: predict
                input:
                    - trained_model
                    - resample_transform
            classification_report:
                type: evaluator
                evaluator: classification_report
                operation: supervised
                input:
                    - dataset
                    - random_forest_classify
#             confusion_matrix:
#                 type: evaluator
#                 evaluator: confusion_matrix
#                 operation: supervised
#                 input:
#                     - dataset
#                     - random_forest_classify
                
        
                    